### PR TITLE
Return a random entry when a non-existing one is requested

### PR DESCRIPTION
**Pull request by mylk**
If user manipulates the URL to a non-existing entry ID, an empty themed page is rendered.
A random entry can be returned.

### CODE REVIEW

**Comment by mylk** [comment]
Hello guys.

I guess that the webpack bundle has to be ignored from git and generated everytime the server is started.

Changes are not reflected instead the bundle in served.

**Comment by mylk** [comment]
Opened issue https://github.com/tsevdos/greek-in-tech/issues/70 in case thats really an issue.

**Comment by mylk** [comment]
Got the tests passing with your help on issue #70

Unfortunatelly PR still fails. Is there any option on your side to rerun the build?

Thanks in advance.

**Comment by tsevdos** [comment]
nice, I'm merging and check the test this weekend (I'm actually planning to add some more).

**Pull request merged**
